HappinessForm/Controllers/BillingController.cs
using Dapper;
using FormCore.Models;
using HappinessForm.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HappinessForm.Controllers
{
    public class BillingController : Controller
    {
        private readonly HappinessFormContext _db = new HappinessFormContext();
        public static string constr = ConfigurationManager.ConnectionStrings["DashboardContext"].ConnectionString;
        SqlConnection con = new SqlConnection(constr);
        // GET: Billing

        [HttpGet]
        public ActionResult BillinProcess()
        {
            SurgicalInfo model = new SurgicalInfo();


            DateTime start=DateTime.Today;
            DateTime end=DateTime.Today;
            var getPatList = SurgeryReport(start,end);

            model.ListOfEntries = getPatList;



            return View(model);
        }

        [HttpPost]
        public ActionResult BillinProcess(SurgicalInfo model)
        {
           
            var getPatList = SurgeryReport(model.Start, model.End);

            model.ListOfEntries = getPatList;



            return View(model);
        }

        public List<SurgicalInfo> SurgeryReport(DateTime start,DateTime end)
        {
            //var objMTDDetails = SqlMapper.QueryMultiple(con, "RunningPayorMixMTDCountVsRevenueOPDPost", new { facilityId = facilities, endTime = DateTime.Parse(End) }, null, null, commandType: CommandType.StoredProcedure);
            var objDetails = SqlMapper.QueryMultiple(con, "SurgeryReport", new {start = start, end = end }, null, null, commandType: CommandType.StoredProcedure);

          
            var t = objDetails.Read<SurgicalInfo>().ToList();
            return t;
        }


        public ActionResult Details(int Id)
        {
            var objDetails = SqlMapper.QueryMultiple(con, "DetailSurgeryInfo", new { Id = Id }, null, null, commandType: CommandType.StoredProcedure);
            var t = objDetails.Read<SurgicalInfo>().ToList();
           
            SurgicalInfo model= new SurgicalInfo();
            model.ListofLabTest = LabInvest(Id);
            model.Beds = GetBeds();
            foreach (var x in t)
            {
                model.PatientName = x.PatientName;
                model.hospitalNo = x.hospitalNo;
                model.Gender = x.Gender;
                model.Age = x.Age;
                model.ProcedureText = x.ProcedureText;
                model.consultantIncharge = x.consultantIncharge;
                model.AddmisionDate = x.AddmisionDate;
                model.ProcedureDate = x.ProcedureDate;

                model.Diagnosis = x.Diagnosis;
                model.surgeryclassID = x.surgeryclassID;
                model.AnathesiaListId = x.AnathesiaListId;
                model.TheatreListId = x.TheatreListId;
                model.FirstName = x.FirstName;
                model.LastName = x.LastName;
                model.Diagnosistext = x.Diagnosistext;
                model.CoexistingMedConditions = x.CoexistingMedConditions;
                model.SpecialRequirement = x.SpecialRequirement;
                model.CurrentMedication = x.CurrentMedication;
                model.BedID = x.BedID;
                
                model.Beddays = x.Beddays;
                model.BedCost = x.BedCost;

                model.surgeryclassID = x.surgeryclassID;
                model.surgeryCost = x.surgeryCost;

                model.AnathesiaListId = x.AnathesiaListId;
                model.AnathesiaCost = x.AnathesiaCost;

                model.TheatreListId = x.TheatreListId;
                model.TheatreCost = x.TheatreCost;

            }
            return View(model);


        }

        public List<SelectListItem> GetBeds()
        {
            using (StreamReader r = new StreamReader(Server.MapPath("~/JsonFiles/Beds.json")))
            {
                using (JsonTextReader reader = new JsonTextReader(r))
                {
                    reader.SupportMultipleContent = true;
                    JsonSerializer serializer = new JsonSerializer();
                    List<SelectListItem> items = serializer.Deserialize<List<SelectListItem>>(reader);
                    return items;
                }
            }

        }

        public List<Investigations> LabInvest(int Id)
        {
            //var objMTDDetails = SqlMapper.QueryMultiple(con, "RunningPayorMixMTDCountVsRevenueOPDPost", new { facilityId = facilities, endTime = DateTime.Parse(End) }, null, null, commandType: CommandType.StoredProcedure);
            var objDetails = SqlMapper.QueryMultiple(con, "labInvestperPatientPerId", new { Id = Id }, null, null, commandType: CommandType.StoredProcedure);

            Investigations k = new Investigations();
            var t = objDetails.Read<Investigations>().ToList();
            return t;
        }


        

    }
}

HappinessForm/Views/Billing/BillinProcess.cshtml
@model HappinessForm.Models.SurgicalInfo
@using GridMvc.Html
@{
    ViewBag.Title = "BillinProcess";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}



<div class="col-md-8 col-md-offset-2" style="background-color:white">

    @using (Html.BeginForm("BillinProcess", "Billing", FormMethod.Post, new { @class = "card-box", autocomplete = "off" }))
    {

        <div class="form-group">

            <div class="col-sm-3">
                @Html.LabelFor(m => m.Start, new { @class = "col-sm-3" })
                @Html.TextBoxFor(m => m.Start, new { @class = "datepicker  form-control input-sm col-sm-3", @id = "start" })
                @*<span class="input-group-addon bg-custom b-0 text-white"><i class="icon-calender"></i></span>*@
            </div>

            <div class="col-sm-3">
                @Html.LabelFor(m => m.End, new { @class = "col-sm-3" })
                @Html.TextBoxFor(m => m.End, new { @class = "datepicker  form-control input-sm col-sm-3", @id = "end" })
                @*<span class="input-group-addon bg-custom b-0 text-white"><i class="icon-calender"></i></span>*@
            </div>

            <br />

            <button type="submit" class="btn btn-default waves-effect waves-light btn-sm">
                Filter
            </button>

        </div>
    }



    @Html.Grid(Model.ListOfEntries).Columns(columns =>

{


    columns.Add(col => col.hospitalNo).Titled("Hospital Number");
    columns.Add(col => col.PatientName).Titled("Patient Name");
    columns.Add(col => col.ProcedureText).Titled("Procedure").Encoded(false).Sanitized(false);
    columns.Add(col => col.ProcedureDate).Titled("Procedure Date").Encoded(false).Sanitized(false);
    columns.Add()
                .Titled("")
                .SetWidth(10)
                .Filterable(true)
                .Sanitized(false)
                .Encoded(false)
                .RenderValueAs(c => Html.ActionLink("Details", "Details", "Billing", new { id = c.MainId }, null)
                .ToHtmlString());
    columns.Add()
                .Titled("")
                .SetWidth(10)
                .Filterable(true)
                .Sanitized(false)
                .Encoded(false)
                .RenderValueAs(c => Html.ActionLink("Edit", "Edit", "Home", new { id = c.MainId }, null)
                .ToHtmlString());


}).WithPaging(15).Sortable(true)
</div>
    

HappinessForm/Views/Billing/Details.cshtml
@model HappinessForm.Models.SurgicalInfo

@using GridMvc.Html
@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
    ViewBag.Title = "Details";
}
<div class="card-box">
  
    
    <div class="comment">
        <h2 style="margin-left:40px">Details</h2>
      
        <div class="comment-body" style="background-color:white">
            <div class="comment-text">
                <div> <h3 href="#" title="">Patient's Bio-Data</h3></div>
                <div class="form-group clearfix">
                    
                    <div class="col-lg-3">
                        <label style="font-size:small">Patient Name:</label>
                        @Html.DisplayFor(x => x.PatientName, new { @placeholder = "Patient Name*", @class = "form-control  input-sm required", @id = "name", required = "" })
                    </div>
                    <div class="col-lg-3">
                        <label style="font-size:small">Hospital No:</label>
                        @Html.DisplayFor(x => x.hospitalNo, new { @placeholder = "Hospital No*", @class = "required form-control input-sm ", @id = "h", required = "", })
                    </div>
                    <div class="col-lg-3">
                        <label style="font-size:small">Gender:</label>
                        @Html.DisplayFor(x => x.Gender, new { @placeholder = "Patient Name*", @class = "form-control  input-sm required", @id = "name", required = "" })
                    </div>
                    <div class="col-lg-3">
                        <label style="font-size:small">Age:</label>
                        @Html.DisplayFor(x => x.Age, new { @placeholder = "Patient Name*", @class = "form-control  input-sm required", @id = "name", required = "" })
                    </div>
                </div>
            </div>
        </div>
</div>

    <div class="comment">
     
        <div class="comment-body" style="background-color:white">
            <div class="comment-text">
                <div> <h3 href="#" title="">Doctors Med. Report</h3></div>
                <div class="form-group clearfix">
                    
                    <div class="col-lg-3">
                        <label style="font-size:small">Doctor In charge: </label>
                        Dr.
                        @Html.DisplayFor(x => x.LastName, new { @placeholder = "Patient Name*", @class = "form-control  input-sm required", @id = "name", required = "" })
                        @Html.DisplayFor(x => x.FirstName, new { @placeholder = "Patient Name*", @class = "form-control  input-sm required", @id = "name", required = "" })
                    </div>
                    <div class="col-lg-3">
                        <label style="font-size:small">Diagnosis:</label>
                        @Html.DisplayFor(x => x.Diagnosistext, new { @placeholder = "Hospital No*", @class = "required form-control input-sm ", @id = "h", required = "", })
                    </div>
                    <div class="col-lg-3">
                        <label style="font-size:small">Coexisting Med. Conditions:</label>
                        @Html.DisplayFor(x => x.CoexistingMedConditions, new { @placeholder = "Hospital No*", @class = "required form-control input-sm ", @id = "h", required = "", })
                    </div>
                    <div class="col-lg-3">
                        <label style="font-size:small">Procedure:</label>
                        @Html.DisplayFor(x => x.ProcedureText, new { @placeholder = "Patient Name*", @class = "form-control  input-sm required", @id = "name", required = "" })
                    </div>
                    
                </div>
                <div class="form-group clearfix">

                    <div class="col-lg-3">
                        <label style="font-size:small">Special Requirement: </label>
                        @Html.DisplayFor(x => x.SpecialRequirement, new { @placeholder = "Patient Name*", @class = "form-control  input-sm required", @id = "name", required = "" })
                    </div>
                    <div class="col-lg-3">
                        <label style="font-size:small">Current Medication:</label>
                        @Html.DisplayFor(x => x.CurrentMedication, new { @placeholder = "Hospital No*", @class = "required form-control input-sm ", @id = "h", required = "", })
                    </div>
                    <div class="col-lg-3">
                        <label style="font-size:small">Admission Date:</label>
                        @Html.DisplayFor(x => x.AddmisionDate, new { @placeholder = "Hospital No*", @class = "required form-control input-sm ", @id = "h", required = "", })
                    </div>
                    <div class="col-lg-3">
                        <label style="font-size:small">Procedure Date:</label>
                        @Html.DisplayFor(x => x.ProcedureDate, new { @placeholder = "Patient Name*", @class = "form-control  input-sm required", @id = "name", required = "" })
                    </div>
                 
                </div>
            </div>


        </div>
    </div>

    <div class="comment" >

        <div class="comment-body" style="background-color:white">
            <div class="comment-text">
                <div> <h3 href="#" title="">Investigations</h3></div>
                <div class="form-group clearfix">
                    <div class="col-md-2 pull-right">
                        <a href="~/Billing/BillinProcess" type="submit" class="btn btn-default waves-effect waves-light btn-sm">
                            Add Investigation
                        </a>
                    </div>
@Html.Grid(Model.ListofLabTest).Columns(columns =>

{

    columns.Add(col => col.Id, true);
    columns.Add(col => col.InvestigationName).Titled("Investigation Required");
    columns.Add(col => col.Unit).Titled("Unit");
    columns.Add(col => col.Cost).Titled("Cost");
    columns.Add()
            .Titled("")
            .SetWidth(10)
            .Filterable(true)
            .Sanitized(false)
            .Encoded(false)
            .RenderValueAs(c => Html.ActionLink("Delete", "Delete", "Home", new { id = c.Id }, null)
            .ToHtmlString());
}).WithPaging(15).Sortable(true)
                </div>
            </div>


        </div>
    </div>


    <div class="comment" >

        <div class="comment-body" style="background-color:white">
            <div class="comment-text">
                <div> <h3 href="#" title="">Facilities and Services</h3></div>
                <div class="form-group clearfix">

                    <div class="col-lg-4">
                        <label style="font-size:small">Bed Category:</label>
                        @Html.DropDownListFor(x => x.BedID, Model.Beds, "Select BedCategory", new { @class = "form-control select2 input-sm col-sm-3", required = "" })
                    </div>
                    <div class="col-lg-4">
                        <label style="font-size:small">Bed Cost:</label>
                        @Html.DisplayFor(x => x.BedCost, new { @placeholder = "Hospital No*", @class = "required form-control input-sm ", @id = "h", required = "", })
                    </div>
                    <div class="col-lg-4">
                        <label style="font-size:small">Bed Days:</label>
                        @Html.DisplayFor(x => x.Beddays, new { @placeholder = "Patient Name*", @class = "form-control  input-sm required", @id = "name", required = "" })
                    </div>
                    
                </div>

                <div class="form-group clearfix">

                    <div class="col-lg-6">
                        <label style="font-size:small">Surgery Category:</label>
                        @Html.DisplayFor(x => x.surgeryclassID, new { @placeholder = "Patient Name*", @class = "form-control  input-sm required", @id = "name", required = "" })
                    </div>
                    <div class="col-lg-6">
                        <label style="font-size:small">Surgery Cost:</label>
                        @Html.DisplayFor(x => x.surgeryCost, new { @placeholder = "Hospital No*", @class = "required form-control input-sm ", @id = "h", required = "", })
                    </div>
                    

                </div>

                <div class="form-group clearfix">

                    <div class="col-lg-6">
                        <label style="font-size:small">Anathesia Category:</label>
                        @Html.DisplayFor(x => x.AnathesiaListId, new { @placeholder = "Patient Name*", @class = "form-control  input-sm required", @id = "name", required = "" })
                    </div>
                    <div class="col-lg-6">
                        <label style="font-size:small">Anathesia Cost:</label>
                        @Html.DisplayFor(x => x.AnathesiaCost, new { @placeholder = "Hospital No*", @class = "required form-control input-sm ", @id = "h", required = "", })
                    </div>
                   

                </div>
                <div class="form-group clearfix">

                    <div class="col-lg-6">
                        <label style="font-size:small">Theatre Category:</label>
                        @Html.DisplayFor(x => x.TheatreListId, new { @placeholder = "Patient Name*", @class = "form-control  input-sm required", @id = "name", required = "" })
                    </div>
                    <div class="col-lg-6">
                        <label style="font-size:small">Theatre Cost:</label>
                        @Html.DisplayFor(x => x.TheatreCost, new { @placeholder = "Hospital No*", @class = "required form-control input-sm ", @id = "h", required = "", })
                    </div>
                  

                </div>
            </div>


        </div>
    </div>

</div>